image: psachin/emacs-publish:emacs-29.0.50

.build: &build
  script:
  - emacs --batch --no-init-file --load publish.el --funcall org-publish-all
  artifacts:
    paths:
    - public

pages:
  <<: *build
  only:
  - master

test:
  <<: *build
  except:
  - master
