#+title: Handy commands
#+date: <2016-10-09>
#+keywords: gs, ssh, wget, import, mplayer, ffmpeg, convert, git
#+setupfile: ../org-templates/post.org
#+setupfile: ../org-templates/latex-pdf.org
#+LaTeX_HEADER: \lhead{Handy commands}
#+LaTeX_HEADER: \usepackage[a4paper, landscape, margin=0.5in, top=1in, bottom=1in]{geometry}

List of commands that I find useful.

/(Last updated on March 05, 2019)/
** PDF tricks
   - Reduce PDF size
     #+BEGIN_SRC shell
       gs -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/screen -sOutputFile=new_file.pdf original_file.pdf
     #+END_SRC

   - Unlock PDF file
     #+BEGIN_SRC shell
       gs -q -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -sOutputFile=unencrypted.pdf -c .setpdfwrite -f encrypted.pdf
     #+END_SRC

   - Extract pages from PDF file
      #+BEGIN_SRC shell
        gs -sDEVICE=pdfwrite -dNOPAUSE -dBATCH -dSAFER -dFirstPage=1 -dLastPage=3 -sOutputFile=out_file_page_1_to_3.pdf input_file.pdf
      #+END_SRC

   - Merge PDF files
     #+BEGIN_SRC shell
       gs -dBATCH -dNOPAUSE -q -sDEVICE=pdfwrite -sOutputFile=out_file.pdf in_file_1.pdf in_file_2.pdf
     #+END_SRC
** Media tricks
   - Rotate video
      #+BEGIN_SRC shell -n
	# Using mplayer(watch rotated video)
	mplayer -vf-add rotate=1 sample.mp4

	# Using ffmpeg
	ffmpeg -i infile.mp4 -strict -2 -vf "transpose=1" outfile.mp4
      #+END_SRC

   - Convert 3GP to MP4
      #+BEGIN_SRC shell
	ffmpeg -i VID_0050.3gp -strict -2 -q:a 0 -ab 64k -ar 44100 VID_0050.mp4
      #+END_SRC
   - FLV to MP4
      #+BEGIN_SRC shell
	ffmpeg -i input.flv -qscale 1 -ar 22050 output.mp4
      #+END_SRC

   - MKV to MP4
     #+BEGIN_SRC shell
       ffmpeg -i input.mkv -c:v mpeg4 -c:a libmp3lame -b:a 128K output.mp4
       # or you can keep the video stream
       ffmpeg -i input.mkv -c:v copy -c:a aac -b:a 128K output.mp4

       # Convert initial 10 seconds of the video for testing
       ffmpeg -t 10 -i input.mkv -c:v copy -c:a aac -b:a 128K output.mp4
     #+END_SRC

   - [[https://manuals.playstation.net/document/en/ps4/videos/mp_format_v.html][PS4 compatible format]] (Special thanks to the guys at =#ffmpeg@freenode= for helping me converting to the PS4 compatible format)
     #+BEGIN_SRC shell -n
       # Ex1
       ffmpeg -i input.mkv -c:v libx264 -c:a libmp3lame -preset slow -profile:v high -level 4.2 -b:a 320K output.mkv
       # Ex2
       ffmpeg -i input.mkv -c:v libx264 -vf format=yuv420p -c:a libmp3lame -preset slow -profile:v high -level 4.2 -b:a 320K output.mkv
       # Ex3
       ffmpeg -i input.mkv -c:v libx264 -vf format=yuv420p -c:a libmp3lame -preset slow -profile:v high -level 4.2 -crf 21 -b:a 320K output.mkv
       # Ex4
       ffmpeg -i input.mkv -c:v libx264 -vf format=yuv420p -c:a aac -preset slow -profile:v high -level 4.2 -crf 21 -b:a 128K output.mkv
     #+END_SRC

     Refer [[./ffmpeg_libmp3lame.html][this post]] to compile =ffmpeg= with lame & libx264 support.

   - Extract audio(MP3) from MP4 video
      #+BEGIN_SRC shell -n
	ffmpeg -i video.mp4 -f mp3 -ab 192000 -vn music.mp3

	# or specify codec to use `libmp3lame` in this case.
	ffmpeg -i video.mp4 -f mp3 -codec:a libmp3lame -ab 320000 -vn music.mp3
      #+END_SRC

      /where/

      *-i*: input file

      *-f mp3*: file format should be MP3

      *-ab 192000*: audio should be encoded at 192Kbps. 320000 for 320Kbps

      *-vn*: don't want video

   - Cut video starting from 19 min 49 seconds up to 04 mins 18 seconds.
      #+BEGIN_SRC shell
	ffmpeg -y -i Video.mp4 -qscale 1 -ss 00:19:49.0 -t 00:04:18.0 -acodec copy -vcodec copy output.mp4
      #+END_SRC

      /Note/: *-sameq* was removed in the recent version of =ffmpeg=

   - Use =mplayer= to extract audio(MP3)
     #+BEGIN_SRC shell
       mplayer -dumpaudio movie.flv -dumpfile movie_audio_track.mp3
     #+END_SRC
   - Reduce resolution
     #+BEGIN_SRC shell
       ffmpeg -i Birdman.mp4 -strict -2  -s 720x480 birdman.mp4
     #+END_SRC
   - recordmydesktop
     #+BEGIN_SRC shell
       recordmydesktop -x 100 -y 100 --width 1280 --height 720 --freq 48000 --fps 30 -o ~/Videos/recordings/test-video.ogv
     #+END_SRC
   - Include subtitles(Use =subtitleeditor= to create subtitle)
     #+BEGIN_SRC shell
       ffmpeg -i video.avi -vf subtitles=subtitle.srt out.avi
     #+END_SRC

** Image manupulation
   - Capture screenshot
     #+BEGIN_SRC shell
       import -window root screenshot.png
     #+END_SRC
   - Resize image 50% of its original size
     #+BEGIN_SRC shell
       convert dragon.gif -resize 50% half_dragon.gif
     #+END_SRC
   - Control compression level of an image
     #+BEGIN_SRC shell
       convert input.png -quality 75 output.jpg
     #+END_SRC

** Git
   - Find commits by author between the timeline
     #+BEGIN_SRC shell -n
       # Syntax
       git log --since "START" --until "END" --author=AUTHOR --pretty=oneline --diff-filter=A

       # Example
       git log --since "Oct 1 2018" --until "DEC 28 2018" --author=psachin@redhat.com --pretty=oneline --diff-filter=A

       # If you also want to see the file names
       git log --since "Oct 1 2018" --until "DEC 28 2018" --author=psachin@redhat.com --name-status --pretty=oneline --diff-filter=A
     #+END_SRC

** Misc
   - Clean up =~/.ccache/= directory
     #+BEGIN_SRC shell -n
       # View statistics using
       ccache -s

       # Clear cache using
       ccache -C
     #+END_SRC

   - wget a website
     #+BEGIN_SRC bash
       wget -rkp -l5 -np -nH -cut-dirs=1 https://example.com
     #+END_SRC

     /where/

     *-rkp*: recursive, make link suitable for local viewing, download all files needed to properly view the page.

     *-l5*: recursively download 5 links away form the original page.

     *-n*: retrieve files below parent directory.

     *-H*: Span across hosts when doing recursive retrieving.

   - Find the Filesystem/partition of current directory
     #+BEGIN_SRC shell
       df -h .
       # Notice the DOT
     #+END_SRC

   - List commands/applications using IPv4/IPv6
     #+BEGIN_SRC shell -n
       lsof -i 4
       # and
       lsof -i 6

       # Sample output of `lsof -i 6`
       COMMAND     PID    USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
       emacs      3131 psachin   21u  IPv6 4519926      0t0  TCP nubia:55524->rajaniemi.freenode.net:ircu-3 (ESTABLISHED)
       emacs      3131 psachin   22u  IPv6 4524689      0t0  TCP nubia:41416->irc0.acc.umu.se:ircu-3 (ESTABLISHED)
       emacs      3131 psachin   23u  IPv6 4548798      0t0  TCP nubia:33452->strange.oftc.net:ircu-3 (ESTABLISHED)
       firefox    3656 psachin   51u  IPv6 5606852      0t0  TCP nubia:54302->sc-in-xbd.1e100.net:https (ESTABLISHED)
       chrome     3878 psachin  128u  IPv6 4518904      0t0  UDP *:mdns
       chrome     3878 psachin  148u  IPv6 4518906      0t0  UDP *:mdns
       thunderbi 13475 psachin   40u  IPv6 5552262      0t0  TCP nubia:35084->sc-in-x6d.1e100.net:imaps (ESTABLISHED)
       thunderbi 13475 psachin   61u  IPv6 4526804      0t0  TCP nubia:59268->sb-in-x6c.1e100.net:imaps (ESTABLISHED)
       thunderbi 13475 psachin   62u  IPv6 5592285      0t0  TCP nubia:60922->sa-in-x6d.1e100.net:imaps (ESTABLISHED)
       thunderbi 13475 psachin   85u  IPv6 5408348      0t0  TCP nubia:48110->sb-in-x6d.1e100.net:imaps (ESTABLISHED)
       thunderbi 13475 psachin  134u  IPv6 5561644      0t0  TCP nubia:44914->sb-in-x6c.1e100.net:imaps (ESTABLISHED)
     #+END_SRC

#+INCLUDE: "../disquss.inc"
